"use client";

import { useState } from "react";
import { useResearchRun } from "@/hooks/useResearchRun";
import { BriefContent, CompanyIdentity, CompanySearchForm, DomainPicker, Feedback, ReportActions, RetryNotice, ResearchProgress, SourceList } from "@/components/dossier";

export default function Home() {
  const research = useResearchRun();
  const { run, history, usage, pending, error, active } = research;
  const [showUsage, setShowUsage] = useState(false);
  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Skip to content</a>
    <header className="masthead"><button className="brand" onClick={research.newResearch} aria-label="KnowYourCompany home"><span className="brand-mark" aria-hidden="true">k<span>·</span></span><span>KnowYourCompany<small>DO YOUR HOMEWORK. FIND YOUR DIRECTION.</small></span></button><div className="masthead-right"><span className="edition">THE CAREER RESEARCH DESK</span><span className="beta">PRIVATE BETA</span></div></header>
    <div className="workspace">
      <aside className="sidebar"><div className="sidebar-top"><span className="eyebrow">YOUR WORKSPACE</span><button className="new-brief" onClick={research.newResearch} disabled={pending}><span>＋</span> New company brief</button></div><nav aria-label="Saved research"><div className="sidebar-label">ON YOUR DESK <span>{history.length.toString().padStart(2, "0")}</span></div>{history.length ? history.map(saved => <button key={saved.id} className={run?.id === saved.id ? "saved-brief selected" : "saved-brief"} onClick={() => void research.openSaved(saved)} disabled={pending}><span className="saved-initial">{saved.company_name.slice(0, 1).toUpperCase()}</span><span><strong>{saved.company_name}</strong><small>{saved.status.replaceAll("_", " ")}</small></span><span aria-hidden="true">↗</span></button>) : <p className="empty-history">A little research today.<br/>A clearer direction tomorrow.<br/><span>Your briefs will live here.</span></p>}</nav><div className="sidebar-bottom"><button className="usage-toggle" onClick={() => setShowUsage(!showUsage)} aria-expanded={showUsage}>Research allowance <span>{usage ? `${Math.max(0, usage.daily_limit - usage.used_today)} left` : "—"}</span></button>{showUsage && usage && <div className="usage-details"><p>{usage.used_today} of {usage.daily_limit} runs used in the last 24 hours.</p><p>{usage.completed} completed briefs · {usage.cache_hits} reused briefs</p><p>{(usage.input_tokens + usage.output_tokens).toLocaleString()} model tokens</p>{usage.median_compute_seconds !== null && <p>Median research compute: {Math.round(usage.median_compute_seconds)}s</p>}{usage.estimated_llm_cost_usd !== null && <p>Estimated model cost: US${usage.estimated_llm_cost_usd.toFixed(4)}. Excludes search and hosting.</p>}</div>}<p>Saved in this browser session.<br/>Clearing browser data removes access.</p></div></aside>
      <main id="main-content" className="main-content">
        <div className="page-topline"><span>RESEARCH / {run ? "YOUR DOSSIER" : "A FRESH START"}</span><span>PUBLIC EVIDENCE. PERSONAL DIRECTION.</span></div>
        {error && <div className="error-banner" role="alert">{error}</div>}
        {!run ? <>
          <section className="welcome"><div className="welcome-copy"><span className="eyebrow"><span className="tiny-line" /> GO IN WITH CONTEXT</span><h1>Know the company.<br/><em>Find your place.</em></h1><p className="welcome-description">The work they do. The direction they’re taking. Where your skills could fit. Turn scattered information into a company brief worth reading.</p><CompanySearchForm onStart={(name, hint, refresh) => void research.start(name, hint, refresh)} disabled={pending} /></div><aside className="sample-card" aria-label="Example brief structure"><div className="sample-card-top"><span>FIELD NOTES</span><span>NO. 001</span></div><span className="sample-label">A LOOK INSIDE YOUR BRIEF</span><h2>Less searching.<br/>More understanding.</h2><div className="sample-rule" /><ol><li><span>01</span>What the company actually does</li><li><span>02</span>The evidence behind the story</li><li><span>03</span>A career focus that fits</li><li><span>04</span>Your preparation priorities</li></ol><div className="sample-card-footer"><span>Illustrative structure<br/>Your research will be company-specific.</span><span aria-hidden="true">↗</span></div></aside></section>
          <section className="method-strip" aria-label="How research works"><div><span>01 / ESTABLISH</span><h3>Start with the right company.</h3><p>We check the identity before connecting the dots.</p></div><div><span>02 / UNDERSTAND</span><h3>Follow the evidence.</h3><p>Read a focused brief with sources you can inspect.</p></div><div><span>03 / PREPARE</span><h3>Make the next step yours.</h3><p>Pick a career area and build your study priorities.</p></div></section>
          <div className="desk-note"><span aria-hidden="true">↳</span><p>A useful brief tells you what’s known <em>and</em> what isn’t.<br/>Company facts and preparation suggestions stay clearly labelled.</p></div>
        </> : <>
          <div className="dossier-heading"><div><span className="eyebrow">YOUR COMPANY DOSSIER</span><h1>{run.company_name}</h1><p>{run.selected_domain || "From company context to career direction."}</p></div><span className="dossier-number">REF / {run.id.slice(0, 6).toUpperCase()}</span></div>
          <div className="dossier-layout"><div className="dossier-main"><CompanyIdentity run={run} onConfirm={() => void research.confirm()} disabled={pending} />
          {!run.company_brief && active && <div className="pending-brief"><span className="page-outline" aria-hidden="true">01<br/>——<br/>——</span><h2>A clearer picture is taking shape.</h2><p>Checked information will appear here as your research completes.</p></div>}
          {run.company_brief && <><div className="freshness">{run.cached_at ? "Reused verified research" : "Research date"} · {run.researched_at?.slice(0, 10)}{run.cached_at && <span>Start a new brief with fresh research to update it.</span>}</div><BriefContent brief={run.company_brief} label="01 / UNDERSTAND THE COMPANY" title="The company brief" /></>}
          {run.status === "awaiting_domain_selection" && run.company_brief && <DomainPicker brief={run.company_brief} onChoose={domain => void research.chooseDomain(domain)} disabled={pending} />}
          {run.domain_brief && <BriefContent brief={run.domain_brief} label="02 / BUILD YOUR DIRECTION" title={run.selected_domain || "Your preparation"} />}
          {(run.export_status !== "not_started") && <ReportActions run={run} onRetry={() => void research.retry()} disabled={pending} />}
          {["failed", "insufficient_evidence", "cancelled"].includes(run.status) && <section className="outcome-panel"><span className="eyebrow">{run.status === "failed" ? "A STEP NEEDS ATTENTION" : run.status === "cancelled" ? "RESEARCH STOPPED" : "THE EVIDENCE HAS LIMITS"}</span><h2>{run.status === "failed" ? "Your completed work is safe." : run.status === "cancelled" ? "Pick it up when you’re ready." : "We need a clearer starting point."}</h2><p>{run.message}</p>{run.status === "failed" ? <><RetryNotice run={run} />{run.retry_allowed === true && <button className="primary" onClick={() => void research.retry()} disabled={pending}>Retry saved step →</button>}</> : <button className="secondary" onClick={research.newResearch}>Start a new brief →</button>}</section>}
          <SourceList sources={run.sources} />
          {run.company_brief && !active && <Feedback key={run.id} run={run} onSubmit={(rating, comment) => void research.feedback(rating, comment)} disabled={pending} />}
          </div><aside className="activity-rail"><ResearchProgress run={run} connection={research.connection} onCancel={() => void research.cancel()} disabled={pending} /><div className="rail-note"><span className="eyebrow">A NOTE FROM THE DESK</span><p>Preparation advice is a starting point. Always check current hiring details with the company.</p>{run.sources.length > 0 && <a href="#sources">{run.sources.length} sources in your register ↓</a>}</div></aside></div>
        </>}
        <footer className="page-footer"><span>KnowYourCompany / Research with perspective.</span><span>Built for your next chapter.</span></footer>
      </main>
    </div>
  </div>;
}
